version: "3"

tasks:
  lock:
    desc: "lock with update"
    cmds:
      - uv lock --upgrade

  install:
    desc: "install local dependencies"
    cmds:
      - uv sync --all-extras --frozen

  lint:
    desc: "run linters"
    cmds:
      - uv run ruff format .
      - uv run ruff check . --fix
      - uv run mypy .

  lint-ci:
    desc: "run linters"
    cmds:
      - uv run ruff format . --check
      - uv run ruff check . --no-fix
      - uv run mypy .

  tests:
    desc: "run pytest (pass args after '--')"
    cmds:
      - uv run pytest {{.CLI_ARGS}}

  publish:
    cmds:
      - rm -rf dist/*
      - uv tool run --from build python -m build --installer uv
      - uv tool run twine check dist/*
      - uv tool run twine upload dist/* --username __token__ --password $PYPI_TOKEN
