version: "3"

tasks:
  install:
    desc: "install local dependencies"
    cmds:
      - poetry install --sync --no-root --all-extras

  lint:
    desc: "run linters"
    cmds:
      - poetry run ruff format .
      - poetry run ruff check . --fix
      - poetry run mypy .

  lint-ci:
    desc: "run linters"
    cmds:
      - poetry run ruff format . --check
      - poetry run ruff check . --no-fix
      - poetry run mypy .

  tests:
    desc: "run pytest (pass args after '--')"
    cmds:
      - poetry run pytest {{.CLI_ARGS}}
