name: main

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - run: pip install poetry
      - run: task install
      - run: task lint-ci

  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - run: pip install poetry
      - run: task install
      - run: task tests
